services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=potato_db
      - COLLECTION_NAME=tweets
      - SCRIPT=${SCRIPT:-safe_convert_data_types.py}
    

volumes:
  mongodb_data: